
# cargo-vet audits file

[[audits.arrayvec]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
delta = "0.7.2 -> 0.7.4"

[[audits.bellperson]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
version = "0.24.1@git:37b9976bcd96986cbdc71ae09fc455015e3dfac0"
notes = "Fork of the official bellperson owned by Iron Fish"

[[audits.blake3]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
delta = "1.3.3 -> 1.5.0"

[[audits.crypto_box]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
delta = "0.8.2 -> 0.9.1"

[[audits.equihash]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
version = "0.2.0@git:d551820030cb596eafe82226667f32b47164f91b"
notes = "Fork of the official equihash owned by Iron Fish"

[[audits.f4jumble]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
version = "0.1.0@git:d551820030cb596eafe82226667f32b47164f91b"
notes = "Fork of the official f4jumble owned by Iron Fish"

[[audits.frost-core]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
version = "1.0.0"

[[audits.itertools]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
delta = "0.12.1 -> 0.12.0"

[[audits.jubjub]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
delta = "0.9.0 -> 0.9.0@git:a1a0c2ed69eec4d5d5e87842e2a40849f7fa4633"
notes = "Fork of the official jubjub owned by Iron Fish"

[[audits.litrs]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
delta = "0.4.1 -> 0.2.3"

[[audits.zcash_address]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
version = "0.1.0@git:d551820030cb596eafe82226667f32b47164f91b"
notes = "Fork of the official zcash_address owned by Iron Fish"

[[audits.zcash_encoding]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
version = "0.1.0@git:d551820030cb596eafe82226667f32b47164f91b"
notes = "Fork of the official zcash_encoding owned by Iron Fish"

[[audits.zcash_note_encryption]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
delta = "0.1.0 -> 0.1.0@git:d551820030cb596eafe82226667f32b47164f91b"
notes = "Fork of the official zcash_note_encryption owned by Iron Fish"

[[audits.zcash_primitives]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
version = "0.7.0@git:d551820030cb596eafe82226667f32b47164f91b"
notes = "Fork of the official zcash_primitives owned by Iron Fish"

[[audits.zcash_proofs]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
version = "0.7.1@git:d551820030cb596eafe82226667f32b47164f91b"
notes = "Fork of the official zcash_proofs owned by Iron Fish"

[[trusted.halo2_gadgets]]
criteria = "safe-to-deploy"
user-id = 1244 # ebfull
start = "2022-05-10"
end = "2025-03-01"

[[trusted.halo2_proofs]]
criteria = "safe-to-deploy"
user-id = 1244 # ebfull
start = "2022-05-10"
end = "2025-03-01"

[[trusted.orchard]]
criteria = "safe-to-deploy"
user-id = 6289 # str4d
start = "2021-01-07"
end = "2025-03-01"

[[trusted.pasta_curves]]
criteria = "safe-to-deploy"
user-id = 6289 # str4d
start = "2021-03-03"
end = "2025-03-01"

[[trusted.reddsa]]
criteria = "safe-to-deploy"
user-id = 6289 # str4d
start = "2021-01-08"
end = "2025-03-01"

[[trusted.zcash_note_encryption]]
criteria = "safe-to-deploy"
user-id = 6289 # str4d
start = "2021-03-19"
end = "2025-03-01"
