name: Import perf test result
permissions: write-all

on:
  push:
    branches:
      - yajun/ifl-983-output-perf-test-output-to-a-file-in-a-format

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: 'Get artifact url'
        uses: actions/github-script@v6
        id: get-url
        with:
          result-encoding: string
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: '5217915093'
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "perf-test-report"
            })[0];

            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });

            console.log(download)
            return download.url

      - name: Check out repo
        uses: actions/checkout@v2

      - name: Fetch Data
        uses: githubocto/flat@v3
        with:
          http_url: '${{steps.get-url.outputs.result}}'
          downloaded_filename: 'perf-test-report.zip'
