name: Push new version number to API
on:
  push:
    branches:
      - test-push-version-to-api
  workflow_dispatch:
    inputs:
      push_mainnet:
        description: "mainnet"
        type: boolean
        default: false
      push_testnet:
        description: "testnet"
        type: boolean
        default: false

jobs:
  Push:
    name: Push Version to API
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Push version string to mainnet API
        run: ./ironfish-cli/scripts/push-version.sh
        env:
          IRON_FISH_API_KEY: ${{ secrets.IRON_FISH_API_KEY }}
          IRON_FISH_API_URL: ${{ secrets.IRON_FISH_API_URL }}

      - name: Push version string to testnet API
        run: ./ironfish-cli/scripts/push-version.sh
        env:
          IRON_FISH_API_KEY: ${{ secrets.IRON_FISH_API_KEY_TESTNET }}
          IRON_FISH_API_URL: ${{ secrets.IRON_FISH_API_URL_TESTNET }}
