name: Deploy Node Docker Image
on:
  push

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          mask-aws-account-id: true

      - name: Login to AWS Registry
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $AWS_REGISTRY_URL
        env:
          AWS_REGISTRY_URL: ${{ secrets.AWS_NODE_REGISTRY_URL }}

      - name: Build Node Image
        run: ./ironfish-cli/scripts/build-docker.sh

      - name: Deploy Node Image to AWS:${{ github.sha }}
        if: ${{ inputs.aws_tag_git_sha }}
        run: |
          docker tag ironfish ${{ secrets.AWS_NODE_REGISTRY_URL }}/ironfish:multi
          docker push ${{ secrets.AWS_NODE_REGISTRY_URL }}/ironfish:multi
